author:
  name: Fernando Tricas García
  url: https://elmundoesimperfecto.com
  email: web@elmundoesimperfecto.com
  avatar: https://1.gravatar.com/avatar/16fefa5bbee207e96c9d78ad3854995c28c0ac2ef959889e8fea717b6a88f286
  homepage: https://elmundoesimperfecto.com/
footer-links:
  email: web@elmundoesimperfecto.com
  facebook: fernando.tricas
  github: fernand0
  instagram: ftricas
  linkedin: fernand0
  twitter: fernand0
  mastodon: https://mastodon.social/@fernand0
tagline: El mundo es imperfecto, todos podemos hacer algo para mejorarlo.
explanation: Este sitio agrega enlaces a diferentes sitios donde publico textos, imágenes
  y otras actividades.
plugins:
- jekyll-paginate
- jekyll-seo-tag
theme_color: theme-base-0b2
theme_version: 1.0.0
title: El Mundo Es Imperfecto
email: web@elmundoesimperfecto.com
description: 'El mundo es imperfecto, todos podemos hacer algo para mejorarlo. Este
  sitio agrega enlaces a diferentes sitios donde publico textos, imágenes y otras
  actividades.

  '
subtitle: El mundo es imperfecto, todos podemos hacer algo para mejorarlo.
url: https://elmundoesimperfecto.com
baseurl: /
include:
- .well-known
permalink: /:title/
paginate: 100
paginate_path: /page:num/
sass:
  style: compressed
